### ISSUE TITLE
CORS ISSUE

### ISSUE THREAD

**Issue by alusicode** [fagongzi/manba#187]
I am trying to use the api with my backend, but any time i make a request from my front end app, i get CORS error

**Comment by zhangxu19830126** [comment]
The gateway do not process cross-domain requests. If the backend process cross-domain，you can configure the host(front host, or server address, or custom domain name) used for forwarding to the backend in the API,

**Comment by thejsdev** [comment]
my proxy is served on api.thefreelance.dev
while my front end is on thefreelance.dev 
but i keep getting cors,

how ever if i try with post man or send directly to my backend, i dont get errors

**Comment by zhangxu19830126** [comment]
By default, the proxy will using front's request host name

**Comment by thejsdev** [comment]
so how can this issue be likely resolved?
they are both on the same server..

proxi domain should change instead?

**Comment by zhangxu19830126** [comment]
You can use nginx , and configuration like: 
```
server {
    listen 80;
    server_name thefreelance.dev;


    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://api.thefreelance.dev;
    }


    location / {
        root /frond; 
    }
}
```

**Comment by thejsdev** [comment]
so i have two nginx server blocks, this one is for the front end which opens at thefreelance.dev
and exposes a docker container running at port 8083



server {


        server_name thefreelance.dev www.thefreelance.dev;

        location / {
               proxy_pass   http://127.0.0.1:8083;
                 proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
           proxy_set_header Host $host;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/thefreelance.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/thefreelance.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot




}


server {
    if ($host = www.thefreelance.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = thefreelance.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;


        server_name thefreelance.dev www.thefreelance.dev;
    return 404; # managed by Certbot




}







then this is my my proxy nginx block, i want it to be accessed on api.thefreelance.dev ,
the proxy is running on docker and it exposes port 90,

i tried to configure cors before but didnt work...



server {



        server_name api.thefreelance.dev;

        location / {
               proxy_pass   http://127.0.0.1:90;
               

               if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
     }
        }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api.thefreelance.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.thefreelance.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = api.thefreelance.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;



        server_name api.thefreelance.dev;
    return 404; # managed by Certbot


}

**Comment by zhangxu19830126** [comment]
Only one nginx needed. 
```
upstream api.thefreelance.dev {
    server 127.0.0.1:90  // proxy address
}


server {
    listen 80;
    server_name thefreelance.dev www.thefreelance.dev;

    # api configuration
    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://api.thefreelance.dev;
    }


    # your front configuration
    location / {
        root /frond; 
    }
}

```

**Comment by zhangxu19830126** [comment]
frond access www.thefreelance.dev or thefreelance.dev to get html page. and js use www.thefreelance.dev/api/xxx or thefreelance.dev/api/xxx to access your api

**Comment by thejsdev** [comment]
my front end is built with react, running on port 8083, how do i add it to that location block, that the issue

**Comment by zhangxu19830126** [comment]
```
upstream api.thefreelance.dev {
    server 127.0.0.1:90  // proxy address
}


upstream www.thefreelance.dev {
    server 127.0.0.1:8083  // front react address
}

server {
    listen 80;
    server_name thefreelance.dev www.thefreelance.dev;

    # api configuration
    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://api.thefreelance.dev;
    }


    # your front configuration
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://www.thefreelance.dev;
    }
}
```

**Comment by thejsdev** [comment]
let me try this.. but does it mean now i have to access the api like 
thefreelance.dev/api instead of api.thefreelance.dev

i really wanted it to be the later

**Comment by zhangxu19830126** [comment]
Yes, you try first

**Comment by thejsdev** [comment]
i have tried it, the front end site loads correctly but if i try to make a request to 
thefreelance.dev/api/health
i get 502 bad gateway


/health is an api i registered through the gateway web ui.. it ought to return health status of some service

**Comment by thejsdev** [comment]
<img width="990" alt="Screenshot 2019-11-29 at 9 12 30 AM" src="https://user-images.githubusercontent.com/20558070/69854068-7241f980-1288-11ea-82a4-01c1cf6f83e4.png">
Heres the backlog of the proxy.. running on port 90..

**Comment by zhangxu19830126** [comment]
you must define the api with "/api/health"，or remove the `api` prefix on the nginx

**Comment by thejsdev** [comment]
i am totally lost.. i am using this api gateway to proxy my back end services

i have a service that returns a response when i make get request to "/health"

are you saying i should rewrite it to be api/health?

**Comment by zhangxu19830126** [comment]
The proxy received a request `/api/health`，but you define a API `/health` on the web ui,  so not match. You need to let proxy received `/health`, so you can confige the nginx to do this.

**Comment by thejsdev** [comment]
Still not working.. 
this I what I want to achieve 

I have the web UI for the gateway running on port 9093 and I want it to be - http://gateway.mydomain.dev


Then the app front end app should run on 
http://mydomain.dev 


Then the proxy with connects to my docker services runs on port 90, I want it to be accessible at api.mydomain.dev


Is this possible?

**Comment by thejsdev** [comment]
Please tell me if this possible or is there a way around it .. I have tried the first approach you suggested still didn’t work .. what should I do now please

**Comment by zhangxu19830126** [comment]
```bash
upstream api.thefreelance.dev {
    server 127.0.0.1:90  // proxy address
}


upstream www.thefreelance.dev {
    server 127.0.0.1:8083  // front react address
}

server {
    listen 80;
    server_name thefreelance.dev www.thefreelance.dev;

    # api configuration
    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://api.thefreelance.dev/;    // remove the /api prefix to forward request to gateway
    }


    # your front configuration
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://www.thefreelance.dev;
    }
}
```

You can use `www.thefreelance.dev/api/heatch` to access the `/heath` api

**Comment by thejsdev** [comment]
Hello, i tried this method but it didn't work out so we've decided to move our api gateway to the same host..

our api proxy runs at   mysite.com/api
 i have a service that i want to access with mysite.com/api/accounts

but the proxy keeps sending requests  to the backend with api/accounts which returns 404, please how do i resolve this

**Comment by thejsdev** [comment]
is there a way to set this in the api gateway that i am not aware of or the problem is with nginx

**Comment by archfish** [comment]
> is there a way to set this in the api gateway that i am not aware of or the problem is with nginx

@thejsdev  Can you provide your config and log?

**Comment by valpa** [comment]
The problem is accurately in browser. Firefox and Chrome are not allowing CORS. The browser will first send OPTION to the requested api.

I have a backend application support CORS *.
Then:
Front end UI ( www.mydomain.com) ---(HTTP OPTION)--> Backend API (api.mydomain.com/api)  success. Then Front end send HTTP GET/POST/PUT to backend

Using API gateway:
Front end UI ( www.mydomain.com) ---(HTTP OPTION)--> GATEWAY (api.mydomain.com/api)  fail before forwarding the HTTP OPTION request to backend

**Comment by zhangxu19830126** [comment]
You can use "*" for http method to forwarding the HTTP OPTION request to the backend
