### ISSUE TITLE
Not getting response from server

### ISSUE THREAD

**Issue by alusicode** [fagongzi/manba#188]
When i make a request to my backend without passing through the proxy, i get responses for error if there is any, but when i do with proxy i get empty response, 
could it be in the config and i am not aware due to the language used?

**Comment by zhangxu19830126** [comment]
All requests> = 400 are considered errors. The gateway will give up reading the body, return the error code directly, or wait for retry. If the error message of the body contains business meaning, it is recommended that you use a 200 status code and use the business field to identify the error. For example, define a structure that returns: `{" code ": bizCode," data ":" biz data "," err ":" error message "}`
