### ISSUE TITLE
docker-compose up -d fail

### ISSUE THREAD

**Issue by valpa** [fagongzi/manba#195]
Try to run `docker-compose up -d`, but got error:

```
apiserver_1  | ./entrypoint.sh: exec: line 52: manba-apiserver: not found
proxy_1      | ./entrypoint.sh: exec: line 52: manba-proxy: not found
```

**Comment by zhangxu19830126** [comment]
Because "https://github.com/fagongzi/manba" was renamed from "https://github.com/fagongzi/gateway", but the docker image is not update.

**Comment by zhangxu19830126** [comment]
Upload the new docker image,  retry
