### ISSUE TITLE
Push gate not accessible 

### ISSUE THREAD

**Issue by alusicode** [fagongzi/manba#198]
i can not view the gate way ui at http://127.0.0.1:9093/ui/index.html,
even by running the docker compose in this repo to make sure i am getting the configs right

please help

**Comment by zhangxu19830126** [comment]
First, clone the manba, then run `docker-compose up`,  make sure all exported port in the `docker-compose.yml` are not used.

**Comment by zhangxu19830126** [comment]
It's a BUG, pull the docker image again, and retry.
