### ISSUE TITLE
前端页面不一致问题

### ISSUE THREAD

**Issue by laoluotuo** [fagongzi/manba#202]
发现用docker-compose启动的前端和手动编译的gateway-ui-vue前端有页面不一致的情况, 是在添加API的页面"url重写规则"这块. 问下, 是否docker镜像里的页面是最新版? 如果是, 可否更新到 https://github.com/fagongzi/gateway-ui-vue 里?
谢谢!

**Comment by zhangxu19830126** [comment]
docker-compose里面使用的是gateway-ui-vue 3.0的分支。
