### ISSUE TITLE
如何配置API的HTTPS访问

### ISSUE THREAD

**Issue by laoluotuo** [fagongzi/manba#203]
为API规则配置了"https支持", 添加了证书, 但是不生效. 看proxy日志, 证书配置已经加载上了.
添加参数-addr-https=192.168.66.211:443, 重启proxy443仍然无法打开. 日志中也没体现.
我的proxy, apiserver都是master分支的. 但是尝试过编译v3.0.0分支, 包编译无法通过, 多个包拉不到或版本不对. 于是从fagongzi/manba-proxy:latest里把二进制文件manba-proxy拷了出来启动, 问题依旧.
请问如何解决?

**Comment by zhangxu19830126** [comment]
启动日志看一下，还有启动参数

**Comment by laoluotuo** [comment]
启动命令:
/data/manba/dist/manba-proxy -log-file proxy.log --addr=192.168.66.211:80 -addr-https=192.168.66.211:443 --addr-rpc=192.168.66.211:9091 --addr-store=etcd://192.168.66.211:2379 --namespace=test &
启动日志:
2020/02/24 02:39:50.833818 [info] filter added, filter=<PREPARE>
2020/02/24 02:39:50.833888 [info] start server check worker
2020/02/24 02:39:50.833904 [info] filter added, filter=<WHITELIST>
2020/02/24 02:39:50.833912 [info] filter added, filter=<BLACKLIST>
2020/02/24 02:39:50.833918 [info] filter added, filter=<CACHING>
2020/02/24 02:39:50.833925 [info] filter added, filter=<ANALYSIS>
2020/02/24 02:39:50.833930 [info] filter added, filter=<RATE-LIMITING>
2020/02/24 02:39:50.833934 [info] filter added, filter=<CIRCUIT-BREAKER>
2020/02/24 02:39:50.833940 [info] filter added, filter=<HTTP-ACCESS>
2020/02/24 02:39:50.833949 [info] filter added, filter=<HEADER>
2020/02/24 02:39:50.833957 [info] filter added, filter=<XFORWARD>
2020/02/24 02:39:50.833961 [info] filter added, filter=<VALIDATION>
2020/02/24 02:39:50.833968 [info] filter added, filter=<JS-ENGINE>
2020/02/24 02:39:50.837672 [info] load proxies
2020/02/24 02:39:50.837801 [info] router start watch meta data 
2020/02/24 02:39:50.837823 [info] watch event at: </test>
2020/02/24 02:39:50.840094 [info] proxy <0000192.168.66.211:80> added
2020/02/24 02:39:50.840132 [info] load clusters
2020/02/24 02:39:50.841045 [info] cluster <1> added, data <id:1 name:"test" >
2020/02/24 02:39:50.841074 [info] cluster <1005> added, data <id:1005 name:"test1" >
2020/02/24 02:39:50.841084 [info] cluster <1009> added, data <id:1009 name:"cmdb" >
2020/02/24 02:39:50.841088 [info] load servers
2020/02/24 02:39:50.841711 [info] analysis: added, key=<1002> interval=<1s>
2020/02/24 02:39:50.841804 [info] server <1002> added, data <id:1002 addr:"192.168.66.214:8080" maxQPS:5000 >
2020/02/24 02:39:50.841834 [info] analysis: added, key=<1006> interval=<1s>
2020/02/24 02:39:50.841846 [info] server <1006> added, data <id:1006 addr:"192.168.66.212:8080" maxQPS:5000 >
2020/02/24 02:39:50.841872 [info] analysis: added, key=<1010> interval=<1s>
2020/02/24 02:39:50.841880 [info] server <1010> added, data <id:1010 addr:"192.168.66.243:5000" maxQPS:1000 >
2020/02/24 02:39:50.841884 [info] load binds
2020/02/24 02:39:50.841928 [warning] server <1002> heath check not setting
2020/02/24 02:39:50.841934 [warning] server <1006> heath check not setting
2020/02/24 02:39:50.841952 [info] server <1002> changed to Up
2020/02/24 02:39:50.841956 [info] server <1006> changed to Up
2020/02/24 02:39:50.841959 [warning] server <1010> heath check not setting
2020/02/24 02:39:50.841964 [info] server <1010> changed to Up
2020/02/24 02:39:50.842474 [info] bind <1,1002> created
2020/02/24 02:39:50.843215 [info] bind <1005,1006> created
2020/02/24 02:39:50.843949 [info] bind <1009,1010> created
2020/02/24 02:39:50.843976 [info] load apis
2020/02/24 02:39:50.845971 [info] api <1001> added, data <id:1001 name:"getdomains" urlPattern:"/dnsaas/domains" method:"*" domain:"192.168.66.212" status:Up defaultValue:<cookies:<name:"sdf" value:"sdfd" > code:500 > nodes:<clusterID:1 urlRewrite:"/dnsaas/domains$(origin.header.Path)" > maxQPS:50000 useTLS:true tlsEmbedCert:<certData:"0\202\003\3410\202\002\311\240\003\002\001\002\002\024#\325\350\214\200<(\256\255\314k\344\270\340\014\2606Z\001V0\r\006\t*\206H\206\367\r\001\001\013\005\0000g1\0130\t\006\003U\004\006\023\002CN1\0210\017\006\003U\004\010\023\010Shanghai1\0210\017\006\003U\004\007\023\010Shanghai1\0140\n\006\003U\004\n\023\003k8s1\0170\r\006\003U\004\013\023\006System1\0230\021\006\003U\004\003\023\nkubernetes0\036\027\r180416071100Z\027\r280413071100Z0m1\0130\t\006\003U\004\006\023\002CN1\0210\017\006\003U\004\010\023\010Shanghai1\0210\017\006\003U\004\007\023\010Shanghai1\0270\025\006\003U\004\n\023\016system:masters1\0170\r\006\003U\004\013\023\006System1\0160\014\006\003U\004\003\023\005admin0\202\001\"0\r\006\t*\206H\206\367\r\001\001\001\005\000\003\202\001\017\0000\202\001\n\002\202\001\001\000\360\230i\303.\314\254\350\337\244L\230\374{\251\363\356`\347\020\032\035\2206\376|C\343E\263\352\353o\313\000\372uR\225\234\035E}\237\320\350d\241\277ue\003\335\3350\376Ik\035\301cm\255\210\360\212Ohn\240\362\005\037G\301\261\355\2635\321\177\3014\005\362\276\325\3009.\325\247\203\220^\307\337\244\331\311\036\377\322\324\363tRSR\t\251>\251Zs\200<\337K\036\361\372\t\220\266(\010R\275\030\014%\354x\254\320$\205\346H_\342\230\000\244\341O\270q\026\005\350\375B\027\033\327G\205a\003H\264aq \242\250!'\237R\200\211\253s;\243?K\177M\341Lns\214/\316\031\204)p\222``\333\371e^.\222\306\322\354\246\000!}z\226\236\367\020\014\201\331\261\300\n\367?\315\355\004\314\2038\014\366\213q\017U\365m\257*\267\262\225V\367\355\355\326b*\t5y\007\177\324\016\025\002\003\001\000\001\243\1770}0\016\006\003U\035\017\001\001\377\004\004\003\002\005\2400\035\006\003U\035%\004\0260\024\006\010+\006\001\005\005\007\003\001\006\010+\006\001\005\005\007\003\0020\014\006\003U\035\023\001\001\377\004\0020\0000\035\006\003U\035\016\004\026\004\024\264\335Q\267\016\371\363D\314\3705\304\356;\255\337q\301\257!0\037\006\003U\035#\004\0300\026\200\024#E]u\271\264\370x\327%\016'\377\304\321\005 I\331\3430\r\006\t*\206H\206\367\r\001\001\013\005\000\003\202\001\001\000{\242\251.%\202\270\241\226^R\013zE\300,D\367\347\371\001Kh\021b4\252t\241\321+\256 \023Z\251\204\014R\206[F]\264\364\307\363U\317\t\005vO[/\371\243\026\2768;\345oO\275\206-\242p\371\334.\225\\N\274\314\340\247\264l\222[\372@q\t\200\335s\241U\264M\246I\243\022\342\346\203+\310\204\352\345j~|\010A$B\224\320\256\003mGj\326\010\007\272\0056\351\304\216`i\324\r\227\373\220\274J'JO\177:\246\035h\345. \315FV\316q\252\360bL\231\2532\3771\304^\3745\215\277\237\262\323a\213\317S^H1oA\261y\217#q$\220={oE\211\303L\004\313\2240\352Y\253U'\330\275\tUun\037\030@0\253{Pp\027\303\215d\035\305\324\003W\313/\325e\357\026\365\356\326j:\025\347|_\022C\025/S\240M\023\370BX\270\022\312" keyData:"0\202\004\244\002\001\000\002\202\001\001\000\360\230i\303.\314\254\350\337\244L\230\374{\251\363\356`\347\020\032\035\2206\376|C\343E\263\352\353o\313\000\372uR\225\234\035E}\237\320\350d\241\277ue\003\335\3350\376Ik\035\301cm\255\210\360\212Ohn\240\362\005\037G\301\261\355\2635\321\177\3014\005\362\276\325\3009.\325\247\203\220^\307\337\244\331\311\036\377\322\324\363tRSR\t\251>\251Zs\200<\337K\036\361\372\t\220\266(\010R\275\030\014%\354x\254\320$\205\346H_\342\230\000\244\341O\270q\026\005\350\375B\027\033\327G\205a\003H\264aq \242\250!'\237R\200\211\253s;\243?K\177M\341Lns\214/\316\031\204)p\222``\333\371e^.\222\306\322\354\246\000!}z\226\236\367\020\014\201\331\261\300\n\367?\315\355\004\314\2038\014\366\213q\017U\365m\257*\267\262\225V\367\355\355\326b*\t5y\007\177\324\016\025\002\003\001\000\001\002\202\001\001\000\204\263[\3526\276\327C\336N-\235W\355\021Q$\222\267\377.\230M\271\267el\300F\352\264P\305)O\321\324\262\007(\303\020W\370\264\355\350\3139\341\223$\255\323Y9w\337'\333In\355\377\020\305\010\205N7a%\250\032\030\340}}\221\332\212?R\345P\375&\302N\007\341\371\361\333\310\033/\344)\346\377=\024\3315\252[\331\356\356\2735\177\215\017\025\224\375\207\336z\222q\202*\246+\347\374\331\232\021\326x\2262.\315\261afb;\022Q.\216u\322\267y[\330\322vD%d}FQ6\324\222\207\257/}\365\027\2536\301\345\324~Xqo\326y\254\315\366\316_\321j\362:@\336\371\206\231;\206\216W\024\312[\024\246\375Qi\240\220\005w\002\214\276u\236\243\327*\364\364p\007\"\377w4\213Aq\342!\274\r\362\013r\350\020\326P\271\031\3704\331*\347\310\265\007\224G\227p\241\002\201\201\000\361\\:\216\301w0T\257\272\024D\260{HJ\007+\000s\366\215\002)b\340\226\272\221\326\000\222\205\202\022b\322\374\371fg@\270\353\037/\301\356\360E\370\346,\257\361v%\2251\267\020\264\254:\334UP2\316\322<\363\204\363\227y\362\275\\\037\306\365SF\016\357\231/b\360\037\207\"\337\027k\354\320\361\341\343`\372)\007\003\rq\24215w\366\356\353\303\236\207\210\353\020hP\343uI^M\002\201\201\000\3770N\243=B\274\242f\265\350!\244\376\317w\022\245\251t\336\271\221\322p\276\022{5kD~\235i8^D\233\265\314\\\357\3117\020\224\354\341+\263\217\372\372\337\251\203}\315\264c\211\312\251\330\264\331\024\032@E\356\275\004\257\200\224nq\201 \207\2632\254\373/S\334\301-i\216hX\235(,(\215\301\275\263BQP\342\027\337\036\312/\363\324\013D\021\346\025\321E\223B\034/\021#\"\351\002\201\2002&\030\240\252\300\n\021\276\205jJ\257d\236+\213{\272\327]f\005\t\366Zu\327\004\0204\004=\253>\010\274\220\005}\352|?/\323F\010\004\216u\353v_\330\232\322\022\223\002Fh92\003\364\335\341\020\375z\037a\365\300\353;R]W\363\336R\000\340p\240\005\363\033\232\212\342x3dYoV&\273\351\223\257\306\260\207H\326\320}j\377\247\026\023t\214\316\332{\004\350\267\315\333\003\310\215\002\201\201\000\260\261\200!\243OLQ\236\220\241\324y\354=6\223`\305~\270\241\001\t\027+d\234\217\026`\354\322\215\202\21431%\246\005K\272\2458\004\006(\273\033\257\273\366m[pBqfO\355\236\270\017\346\330\320\004\2050f\347\326\020\267\025\017\213\343\376\3446\376\005\254>\316\360q\211\302&\352\265@\314\n\027b`\035\273\273U\226\215\226=\325\221\345\266\014\302h5\204|\342\324+\354\200\233N`g\321\002\201\200Y\222\327\355\303'9\277WW\301\005m$\335\r\300\201Y\3523d\325\250M\203\240\3638P\344\373#?\321Ue\236@@\346\276\341\357oB\225\370\200\2730\3625X0\337\037g~0\016\361\252\003\323\237{2\010_k6\250e\023\027W\205\254\037\327~\321/\r\342%\240\363\020\036 \2162N\252\004\312N#@h\273\331\315l7\322D\rb2\2055B\212\235}X\210\264\2668\021<\262+\341" > >
2020/02/24 02:39:50.846163 [info] api <1008> added, data <id:1008 name:"cmdb" urlPattern:"/cmdb/base/collections/env/" method:"*" domain:"---" status:Up defaultValue:<body:"Bad backend" code:500 > nodes:<clusterID:1009 readTimeout:1000000000 > useDefault:true >
2020/02/24 02:39:50.846173 [info] load routings
2020/02/24 02:39:50.847133 [info] routing <1004> added, data <id:1004 clusterID:1005 conditions:<parameter:<name:"Router" source:Header > expect:"SPLIT" > strategy:Split trafficRate:70 status:Up api:1001 name:"splitflow" >
2020/02/24 02:39:50.847172 [info] routing <1007> added, data <id:1007 clusterID:1005 conditions:<parameter:<name:"browser" source:FormData > expect:"ie" > strategy:Split trafficRate:50 api:1001 name:"FormData" >
2020/02/24 02:39:50.847177 [info] load plugins
2020/02/24 02:39:50.847640 [info] load applied plugins
2020/02/24 02:39:50.848030 [info] plugins applied with []
2020/02/24 02:39:50.848136 [info] metric: disable prometheus push client 
2020/02/24 02:39:50.848990 [info] start http at 192.168.66.211:80

**Comment by zhangxu19830126** [comment]
https://github.com/fagongzi/manba/blob/master/pkg/proxy/proxy_https.go#L13:17

**Comment by zhangxu19830126** [comment]
默认的根证书没有填写，参数--default-tls-cert, --default-tls-key两个参数没有填写

**Comment by laoluotuo** [comment]
现在可以了. 貌似没有在教程里呀?
感谢!
