### ISSUE TITLE
UI管理界面哪个地方可以设置接口聚合数据合并字段呢

### ISSUE THREAD

**Issue by lerpo** [fagongzi/manba#211]
没有看到如何把两个接口返回的数据合并在一块
![image](https://user-images.githubusercontent.com/7897329/85944226-b359d380-b967-11ea-9356-2f85296a0c79.png)

**Comment by zhangxu19830126** [comment]
在其他里面，里面有一个重定义接口返回

**Comment by lerpo** [comment]
> 重定义接口返回

**Comment by lerpo** [comment]
> 在其他里面，里面有一个重定义接口返回

Ok 感谢，另外在新建API 通过最后点击提交，我通过查看它调用的apis接口提交的数据，明白了在配置节点的时候，节点标示名就会作为这个节点返回数据的总的字段名，不同的节点返回的数据会通过节点标示名聚合在一块，我的理解应该没差吧
`{
    "code": 0,
    "data": [
        {
            "id": 3,
            "name": "api-useragencies",
            "urlPattern": "/gettwouseragencies/(number):id",
            "method": "GET",
            "domain": "fa.xxx.com",
            "status": 1,
            "nodes": [
                {
                    "clusterID": 1,
                    "urlRewrite": "/api/1/useragencies/$(param.id)",
                    "attrName": "useragenceone",
                    "useDefault": false,
                    "batchIndex": 0,
                    "writeTimeout": 30000000000,
                    "readTimeout": 30000000000,
                    "hostType": 0,
                    "custemHost": ""
                },
                {
                    "clusterID": 1001,
                    "urlRewrite": "/api/1/useragencies/$(param.id)",
                    "attrName": "useragencetwo",
                    "useDefault": false,
                    "batchIndex": 0,
                    "writeTimeout": 30000000000,
                    "readTimeout": 30000000000,
                    "hostType": 0,
                    "custemHost": ""
                }
            ],
            "authFilter": "",
            "useDefault": false,
            "matchRule": 0,
            "position": 0,
            "maxQPS": 3000,
            "rateLimitOption": 0,
            "useTLS": false
        }
    ]
}`
这个attrName就对应于页面上的节点标示名，最终所有返回的数据默认会以attrName配置的名称进行数据聚合

**Comment by lerpo** [comment]
> > 在其他里面，里面有一个重定义接口返回
> 
> Ok 感谢，另外在新建API 通过最后点击提交，我通过查看它调用的apis接口提交的数据，明白了在配置节点的时候，节点标示名就会作为这个节点返回数据的总的字段名，不同的节点返回的数据会通过节点标示名聚合在一块，我的理解应该没差吧
> `{ "code": 0, "data": [ { "id": 3, "name": "api-useragencies", "urlPattern": "/gettwouseragencies/(number):id", "method": "GET", "domain": "fa.xxx.com", "status": 1, "nodes": [ { "clusterID": 1, "urlRewrite": "/api/1/useragencies/$(param.id)", "attrName": "useragenceone", "useDefault": false, "batchIndex": 0, "writeTimeout": 30000000000, "readTimeout": 30000000000, "hostType": 0, "custemHost": "" }, { "clusterID": 1001, "urlRewrite": "/api/1/useragencies/$(param.id)", "attrName": "useragencetwo", "useDefault": false, "batchIndex": 0, "writeTimeout": 30000000000, "readTimeout": 30000000000, "hostType": 0, "custemHost": "" } ], "authFilter": "", "useDefault": false, "matchRule": 0, "position": 0, "maxQPS": 3000, "rateLimitOption": 0, "useTLS": false } ] }`
> 这个attrName就对应于页面上的节点标示名，最终所有返回的数据默认会以attrName配置的名称进行数据聚合

通过我提交的API配置，我去请求/gettwouseragencies/(number):id" 这个接口，它只返回了一个节点的数据并没有出现我想的这样的结果：{useragenceone:{ ....  } ,useragencetwo:{  ...  } } 是我有什么地方还是配置的不对么？

**Comment by zhangxu19830126** [comment]
https://github.com/fagongzi/manba/blob/master/docs-cn/api.md#%E8%81%9A%E5%90%88%E8%AF%B7%E6%B1%82
