### ISSUE TITLE
压测存在500的报错

### ISSUE THREAD

**Issue by chenxiao1990** [fagongzi/manba#215]
不适用manba，直接压测gin的http接口
压测一个ping接口（可以理解为hello world）
![image](https://user-images.githubusercontent.com/16933565/88783549-834d5c80-d1c1-11ea-8cde-e9d290e4591e.png)
2000次 失败数为0.

使用manba网关后
![image](https://user-images.githubusercontent.com/16933565/88783693-b1cb3780-d1c1-11ea-9f2b-b0f8fb64ea54.png)
会出现113个 500的返回。
proxy是直接拉取的master编译的。
压测工具是github中开源的go-stress-testing 。

请问可能是哪里出了问题？

**Comment by zhangxu19830126** [comment]
https://github.com/fagongzi/manba/blob/master/docs-cn/optimization.md

**Comment by chenxiao1990** [comment]
修改了一下net.core.somaxconn=1024还是会有500错误
这个proxy的启动配置
![image](https://user-images.githubusercontent.com/16933565/88871165-c6eba900-d249-11ea-8a37-174c01f73ab5.png)

![image](https://user-images.githubusercontent.com/16933565/88871073-8855ee80-d249-11ea-86a1-1f0d678db8d3.png)

**Comment by zhangxu19830126** [comment]
仔细看文档。应该是连接池不够用的问题。

**Comment by chenxiao1990** [comment]
ok 调整了 limit-conn 可以了  , 默认是64 。
