### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by lvphpwb** [fagongzi/manba#222]
是不是不支持  multipart/form-data

**Comment by zhangxu19830126** [comment]
是的，不支持

**Comment by lvphpwb** [comment]
看了一下fasthttp的代码   如果是multipart/form-data在初始化request的时候直接用的ContinueReadBody创建了multipartForm，没有对body在赋值了，所有copyto的时候body没有拷贝过去

`func copyRequest(req *fasthttp.Request) *fasthttp.Request {
	newreq := fasthttp.AcquireRequest()
	newreq.Reset()
	req.CopyTo(newreq)
	if len(string(req.Header.MultipartFormBoundary())) > 0 {
		newreq.SetBody(req.Body())
	}
	return newreq
}`

不知道这样修改有没有什么问题    我测试是可以了

**Comment by lvphpwb** [comment]
也可以等fasthttp的新版本  新版本应该会修复这个问题

**Comment by gitsrc** [comment]
This is because fasthttp treats multipart/form-data differently and already pre-parses it. You can disable this by setting Server.DisablePreParseMultipartForm = true

**Comment by lvphpwb** [comment]
Server.DisablePreParseMultipartForm = true
