### ISSUE TITLE
URL重写， 前缀不一致怎么处理

### ISSUE THREAD

**Issue by eddyyuen** [fagongzi/manba#226]
在文档里看到可以这样做：
**URL重写**
比如，现在需要给A业务和B业务的接口添加版本的前缀，在不修改后端接口的情况下，可以利用URL重写来实现：

> curl -X PUT -H "Content-Type: application/json" -d '{"name":"查询用户信息接口2","urlPattern":"^/v1/users/(.*)$","method":"GET","status":1,"nodes":[{"clusterID":业务A对应的ID,"urlRewrite":"/users/$1"}]}' http://192.168.0.11:9093/v1/apis

但是现在新的版本已经不能这样写了，会报错。
"urlPattern":"^/v1/users/(.*)$"
"urlRewrite":"/users/$1"

请问现在要怎么处理才能实现上述的功能？

**Comment by zhangxu19830126** [comment]
看文档 https://github.com/fagongzi/manba/blob/master/docs-cn/api.md#%E6%94%AF%E6%8C%81url%E9%87%8D%E5%86%99

**Comment by eddyyuen** [comment]
文档里并没有说明如何处理。
通常我们处理API转发，这样的：/userapi/*  ，转发到后端的接口是： /user/*
/uaerapi  与 /user 两者并不一致。尝试了多个方法都不能实现这样的转发。

**Comment by eddyyuen** [comment]
想要实现的是：
原始URL  /userapi/v1/user/get?userid=123
后端   /api/v1/user/get?userid=123
