### ISSUE TITLE
服务重复注册问题

### ISSUE THREAD

**Issue by shanjunmei** [fagongzi/manba#227]
最近在打算使用它作为生产项目使用，我自己扩展了服务注册功能，和api注册功能，但是实际使用过程中发现，服务会重复注册，我看了下源码，服务注册没有做防重复判断，所有的key都是自增生成的，如果换一个模式，我们使用服务信息做为key的一部分，会不会好很多呢，api注册的地方，我也发现，检查重复的逻辑是加载所有数据去检查，感觉可以修改一下key的 使用api/服务信息去生成，这样，防止重复的判断就好做了很多，不知道这样是有其它的坑吗，因为刚接触这个项目，go也是初学者不到两周

**Comment by zhangxu19830126** [comment]
目前manba的server注册是从页面创建的，然后去etcd分配一个uint64的id，然后存储再etcd里面。所有的manba的元数据都有一个唯一的uint64的和业务无关的id。去重目前没有做，如果做自动服务注册，可以使用服务的地址来去重。ID的分配方式建议不要修改。

**Comment by shanjunmei** [comment]
> 可以使用服务的地址来去重。ID的分配方式建议不要修改。

好吧，花了两个小时，改完，测试时候发现，其它都ok，但是分页失效了，仔细研究了下，发现etcd的分页    没有offset 支持，只好在服务注册的时候，同步注册了一个冗余的key做检查重复使用，已经搞定了
