### ISSUE TITLE
不同微服务怎么设置URL匹配规则

### ISSUE THREAD

**Issue by kay07** [fagongzi/manba#228]
目前存在这种情况：有两个微服务
微服务1的地址：192.168.0.170:9090
微服务1的api包括：/v/s1,/v/s2
微服务2的地址：192.168.0.170:9091
微服务2的api包括：/v/s1,/v/s2
也就是说微服务1和2具有不同的端口号，但是api接口却是一样的。
这样的话改怎么设置API中的url匹配规则？如下图：
![image](https://user-images.githubusercontent.com/40294040/125877306-1e314608-25a1-491a-9c68-14e3785b16c6.png)

**Comment by zhangxu19830126** [comment]
一样得URL就认为是一样得功能，无法区分

**Comment by kay07** [comment]
明白了，谢谢
