### ISSUE TITLE
depend变量获取不到

### ISSUE THREAD

**Issue by crazyIceChen** [fagongzi/manba#229]
当我想用depend获取上一个请求的结果中的变量时，获取不到，已经设置了优先级的先后顺序  message=$(depend.pid.message)

**Comment by zhangxu19830126** [comment]
pid配置了么

**Comment by crazyIceChen** [comment]
> pid配置了么

配置了，页面请求是这样
`{"id":4,"name":"分页查询产品","urlPattern":"/product/*","method":"GET","domain":"","status":1,"nodes":[{"clusterID":1,"urlRewrite":"/api/v1/product/bypage$(origin.query)","hostType":0,"attrName":"pid","useDefault":false,"batchIndex":0,"needHttpDefault":false},{"clusterID":1,"urlRewrite":"/api/v1/product/bypage$(origin.query)&message=$(depend.pid.message)&ice=ice","hostType":0,"attrName":"device","useDefault":false,"batchIndex":1,"needHttpDefault":false}],"authFilter":"","useDefault":false,"matchRule":0,"maxQPS":5000,"rateLimitOption":0}`

**Comment by crazyIceChen** [comment]
另外，我这边配置了js 的plugin ，也配置成使用中了，但是也没用生效

**Comment by zhangxu19830126** [comment]
$(depend.pid.message)，pid这个转发请求返回的json数据格式是什么样子的

**Comment by zhangxu19830126** [comment]
js 插件要配置启动的时候加上一个js插件的加载器

**Comment by crazyIceChen** [comment]
> $(depend.pid.message)，pid这个转发请求返回的json数据格式是什么样子的

格式是这样的 
{"code":0,"message":"succeed","data":{"content":xxx}}

**Comment by crazyIceChen** [comment]
> js 插件要配置启动的时候加上一个js插件的加载器

配置启动的时候？  怎么加上js插件的加载器啊，我看文档上没有写啊

**Comment by zhangxu19830126** [comment]
把depend相关的日志贴一下呢？调用的时候的debug级别的日志

**Comment by zhangxu19830126** [comment]
enableJSPlugin               = flag.Bool("js", false, "enable js plugin")， 有个这个，需要启用js插件的能力才可以。文档漏了

**Comment by crazyIceChen** [comment]
> enableJSPlugin = flag.Bool("js", false, "enable js plugin")， 有个这个，需要启用js插件的能力才可以。文档漏了

添加了js启动项可以用了，谢谢

**Comment by crazyIceChen** [comment]
> 把depend相关的日志贴一下呢？调用的时候的debug级别的日志

depend的问题，我已经发现问题，并提交了pull requests。原因是初始化dependParamExpr的时候参数没给完全，导致jsonparser无法正确获取值

**Comment by zhangxu19830126** [comment]
666
