### ISSUE TITLE
URL重写的时候路径变量丢失，有人知道原因吗

### ISSUE THREAD

**Issue by shanjunmei** [fagongzi/manba#230]
如题:
urlPattern= /app/api/resource/GetByType/*

url重写规则=/api/resource/GetByType/*

请求url 类似 /api/resource/GetByType/1 ，最终这个1 没传到服务端去，这个应该怎么配置呢

**Comment by zhangxu19830126** [comment]
请看文档，文档描述很清楚。https://github.com/fagongzi/manba/blob/master/docs-cn/api.md#%E6%94%AF%E6%8C%81url%E9%87%8D%E5%86%99

**Comment by shanjunmei** [comment]
不好意思，之前没注意到还有个params，感谢
